api_login:
    pattern:  /login
    defaults: { _controller: SmartkillAPIBundle:User:login }
    
api_logout:
    pattern:  /logout
    defaults: { _controller: SmartkillAPIBundle:User:logout }
    
api_profile:
    pattern:  /profile
    defaults: { _controller: SmartkillAPIBundle:User:profile }

api_matches:
    pattern:  /matches
    defaults: { _controller: SmartkillAPIBundle:Match:listing }
    
api_start:
    pattern:  /start
    defaults: { _controller: SmartkillAPIBundle:Match:start } 

api_position:
    pattern:  /position
    defaults: { _controller: SmartkillAPIBundle:MatchUser:position }

api_isJoined:
    pattern:  /isJoined
    defaults: { _controller: SmartkillAPIBundle:MatchUser:isJoined }

api_userGames:
    pattern:  /userGames
    defaults: { _controller: SmartkillAPIBundle:MatchUser:userGames }
    
api_killUser:
    pattern:  /killUser
    defaults: { _controller: SmartkillAPIBundle:MatchUser:killUser }
