api_login:
    pattern:  /login
    defaults: { _controller: SmartkillAPIBundle:User:login }
    
api_logout:
    pattern:  /logout
    defaults: { _controller: SmartkillAPIBundle:User:logout }

api_matches:
    pattern:  /matches
    defaults: { _controller: SmartkillAPIBundle:Match:listing }

api_position:
    pattern:  /position
    defaults: { _controller: SmartkillAPIBundle:MatchUser:position }