parameters:
#    smartkill_api.example.class: Smartkill\APIBundle\Example

services:
#    smartkill_api.example:
#        class: %smartkill_api.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
