smartkill_api:
    resource: "@SmartkillAPIBundle/Resources/config/routing.yml"
    prefix:   /api/

smartkill_web:
    resource: "@SmartkillWebBundle/Resources/config/routing.yml"
    prefix:   /
    
_imagine:
    resource: .
    type:     imagine
