<?php

namespace Smartkill\WebBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MatchUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MatchUserRepository extends EntityRepository
{
}
