index:
    pattern:  /
    defaults: { _controller: SmartkillWebBundle:Default:index }

static_contact:
    pattern:  /contact
    defaults: { _controller: SmartkillWebBundle:Default:static, template: contact }
    
static_rules:
    pattern:  /rules
    defaults: { _controller: SmartkillWebBundle:Default:static, template: rules }
    
register:
    pattern:  /register
    defaults: { _controller: SmartkillWebBundle:User:register }

login:
    pattern:  /login
    defaults: { _controller: SmartkillWebBundle:User:login }
    
login_check:
    pattern:  /login_check
    defaults: { _controller: SmartkillWebBundle:User:login }

logout:
    pattern:  /logout
    
profile:
    pattern:  /profile
    defaults: { _controller: SmartkillWebBundle:User:profile }
    
avatar:
    pattern:  /avatar
    defaults: { _controller: SmartkillWebBundle:User:avatar }

user:
    pattern:  /user/{username}
    defaults: { _controller: SmartkillWebBundle:User:public }

user_edit:
    pattern:  /user/{id}/edit
    defaults: { _controller: SmartkillWebBundle:User:edit }
    
user_delete:
    pattern:  /user/{id}/delete
    defaults: { _controller: SmartkillWebBundle:User:delete }

ranking:
    pattern:  /ranking/{page}
    defaults: { _controller: SmartkillWebBundle:User:ranking, page: 1 }
    requirements: { page: "\d+"}


match:
    pattern:  /match/
    defaults: { _controller: SmartkillWebBundle:Match:index, page: 1 }
    requirements: { page: "\d+"}
    
match_add:
    pattern:  /match/add
    defaults: { _controller: SmartkillWebBundle:Match:add }
    
match_show:
    pattern:  /match/{id}/show
    defaults: { _controller: SmartkillWebBundle:Match:show }

match_edit:
    pattern:  /match/{id}/edit
    defaults: { _controller: SmartkillWebBundle:Match:edit }
    
match_delete:
    pattern:  /match/{id}/delete
    defaults: { _controller: SmartkillWebBundle:Match:delete }
    
match_join:
    pattern:  /match/{id}/join
    defaults: { _controller: SmartkillWebBundle:Match:join }
    
match_user_switch:
    pattern:  /match/{id}/user/{user}/switch
    defaults: { _controller: SmartkillWebBundle:MatchUser:switch }
    
match_user_delete:
    pattern:  /match/{id}/user/{user}/delete
    defaults: { _controller: SmartkillWebBundle:MatchUser:delete }
