index:
    pattern:  /
    defaults: { _controller: SmartkillWebBundle:Default:index }

contact:
    pattern:  /contact
    defaults: { _controller: SmartkillWebBundle:Default:contact }
    
register:
    pattern:  /register
    defaults: { _controller: SmartkillWebBundle:User:register }

match:
    pattern:  /match/
    defaults: { _controller: SmartkillWebBundle:Match:index }

match_show:
    pattern:  /match/{id}/show
    defaults: { _controller: SmartkillWebBundle:Match:show }

match_new:
    pattern:  /match/new
    defaults: { _controller: SmartkillWebBundle:Match:new }
    
match_create:
    pattern:  /match/create
    defaults: { _controller: SmartkillWebBundle:Match:create }
    
match_edit:
    pattern:  /match/{id}/edit
    defaults: { _controller: SmartkillWebBundle:Match:edit }
        
match_update:
    pattern:  /match/{id}/update
    defaults: { _controller: SmartkillWebBundle:Match:update }
        
match_delete:
    pattern:  /match/{id}/delete
    defaults: { _controller: SmartkillWebBundle:Match:delete }
        
login:
    pattern:  /login
    defaults: { _controller: SmartkillWebBundle:User:login }
    
login_check:
    pattern:  /login_check
    defaults: { _controller: SmartkillWebBundle:User:login }

logout:
    pattern:  /logout
