index:
    pattern:  /
    defaults: { _controller: SmartkillWebBundle:Default:index }

contact:
    pattern:  /contact
    defaults: { _controller: SmartkillWebBundle:Default:contact }
    
register:
    pattern:  /register
    defaults: { _controller: SmartkillWebBundle:User:register }

login:
    pattern:  /login
    defaults: { _controller: SmartkillWebBundle:User:login }
    
login_check:
    pattern:  /login_check
    defaults: { _controller: SmartkillWebBundle:User:login }

logout:
    pattern:  /logout
    
profile:
    pattern:  /profile/{id}
    defaults: { _controller: SmartkillWebBundle:User:profile, id: null }
    
avatar:
    pattern:  /avatar/{id}
    defaults: { _controller: SmartkillWebBundle:User:avatar, id: null }

user:
    pattern:  /user/{username}
    defaults: { _controller: SmartkillWebBundle:User:public }



match:
    pattern:  /match/
    defaults: { _controller: SmartkillWebBundle:Match:index }

match_add:
    pattern:  /match/add
    defaults: { _controller: SmartkillWebBundle:Match:add }
    
match_show:
    pattern:  /match/{id}/show
    defaults: { _controller: SmartkillWebBundle:Match:show }

match_edit:
    pattern:  /match/{id}/edit
    defaults: { _controller: SmartkillWebBundle:Match:edit }
    
match_delete:
    pattern:  /match/{id}/delete
    defaults: { _controller: SmartkillWebBundle:Match:delete }
    
match_join:
    pattern:  /match/{id}/join
    defaults: { _controller: SmartkillWebBundle:Match:join }
    
match_user_switch:
    pattern:  /match/{id}/user/{user}/switch
    defaults: { _controller: SmartkillWebBundle:MatchUser:switch }
    
match_user_delete:
    pattern:  /match/{id}/user/{user}/delete
    defaults: { _controller: SmartkillWebBundle:MatchUser:delete }

ranking:
    pattern:  /ranking/{page}
    defaults: { _controller: SmartkillWebBundle:User:ranking, page: 1 }
